version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    lll:
      line-length: 120
      tab-width: 1
  exclusions:
    rules:
      - path: "api/"
        linters:
          - lll
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
