version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  lll:
    line-length: 120
    tab-width: 1

issues:
  exclude-rules:
    - path: "api/"
      linters:
        - lll
  exclude-generated: lax
